### ISSUE TITLE
Package panics when attempting to flatten struct with unexported fields

### ISSUE THREAD

**Issue by 2HgO** [chidiwilliams/flatbson#1]
Package panics when attempting to flatten struct with unexported fields

go version: go1.13
OS: macOS mojave (10.14.6)

sample code:
```
package main

import "github.com/chidiwilliams/flatbson"
import "time"
import "fmt"

func main() {
  a := struct {
    B time.Time `bson:"b,omitempty"` // time.Time has 3 unexported fields
  }{time.Now()}
  fmt.Println(flatbson.Flatten(a))
}
```

expected output:
`map[b:2020-05-22 00:20:15.63927 +0100 WAT m=+0.003913472]`

actual output:
```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x11b6640, 0xc00000c300, 0xab, 0x1, 0x1390240, 0xc000016600)
        /usr/local/go/src/reflect/value.go:1014 +0x1bc
reflect.Value.Interface(...)
        /usr/local/go/src/reflect/value.go:1003
github.com/chidiwilliams/flatbson.flattenFields(0x11f5380, 0xc00000c300, 0x99, 0xc000066930, 0xc00001660a, 0x2, 0x1, 0xc00001660a)
        /Users/oghogho/go/pkg/mod/github.com/chidiwilliams/flatbson@v0.1.4/flatten.go:78 +0x3ce
github.com/chidiwilliams/flatbson.flattenFields(0x11ccbe0, 0xc00000c300, 0x99, 0xc000066930, 0x0, 0x0, 0xbb3ae01, 0xc00009bec8)
        /Users/oghogho/go/pkg/mod/github.com/chidiwilliams/flatbson@v0.1.4/flatten.go:67 +0x249
github.com/chidiwilliams/flatbson.Flatten(0x11ccbe0, 0xc00000c300, 0x11ccbe0, 0xc00000c300, 0x103a067)
        /Users/oghogho/go/pkg/mod/github.com/chidiwilliams/flatbson@v0.1.4/flatten.go:42 +0x10e
main.main()
        /Users/oghogho/Desktop/Softcom/tester/main.go:11 +0x75
exit status 2
```

**Comment by chidiwilliams** [comment]
Good catch, thanks. Fixed in v0.2

**Comment by arc-008** [comment]
@chidiwilliams Looks like I'm getting the same issue even in 0.3.0.
_panic: reflect.Value.Interface: cannot return value obtained from unexported field or method_

**Comment by chidiwilliams** [comment]
@8arcturus Could you please share some example code?

The previous example works in v0.3: https://play.golang.org/p/l5iPQug_sQd

**Comment by arc-008** [comment]
Apologize for late reply. We had a temporary work around for this issue. Now we are stuck with the same issue mentioned here.

I'm using a proto generated stub to which I cannot edit unexported fields to add custom tag to omitempty. 

Something like below:

```
type IssueWithUnexported struct {
       state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

       EntityName string `bson:"entityName"`
	SystemName string `bson:"systemName"`
	UniqueId   string `bson:"uniqueId"`
}

var in *IssueWithUnexported
in = &IssueWithUnexported{
  EntityName: "test",
  SystemName: "test",
  UniqueId: "test",
}
flattenedBson, flatErr := flatbson.Flatten(&in) // Would throw the following error
// panic: reflect.Value.Interface: cannot return value obtained from unexported field or method
```
